### ISSUE TITLE
WinRM commands with no output always have 0 exit code

### ISSUE THREAD

**Issue by carpnick** [WinRb/WinRM#154] opened 2015-10-27 18:27 UTC
If no output is returned in the winrm command, it always succeeds.

 While debugging issue https://github.com/chef/knife-windows/issues/311, I found that [this code](https://gist.github.com/carpnick/9c2a4b2292287172cf18)(taken partially from [winrm_session](https://github.com/chef/knife-windows/blob/master/lib/chef/knife/winrm_session.rb) always has a success  (0) exit code.  If you comment out line [16](https://gist.github.com/carpnick/9c2a4b2292287172cf18#file-winrm-failure-example-L16) and uncomment line [17](https://gist.github.com/carpnick/9c2a4b2292287172cf18#file-winrm-failure-example-L17) it exits with the appropriate exit code (100)

Weird so debugging the gem:

# Failure case
Body Sent:
```
<env:Body>
    <rsp:CommandLine>
      <rsp:Command>&quot; exit 100&quot;</rsp:Command>
    </rsp:CommandLine>
  </env:Body>
```

Received:
```
<rsp:ReceiveResponse>
      <rsp:CommandState CommandId='469786EF-ACB4-47D6-AC50-087F05B78CD4' State='http://schemas.microsoft.com/wbem/wsman/1/windows/shell/CommandState/Done'>
        <rsp:ExitCode>0</rsp:ExitCode>
      </rsp:CommandState>
    </rsp:ReceiveResponse>
```

# Expected/Passing use case:
Request:
```
<env:Body>
    <rsp:CommandLine>
      <rsp:Command>&quot;echo hello &amp;&amp; exit 100&quot;</rsp:Command>
    </rsp:CommandLine>
  </env:Body>
```

Response:
```
<s:Body>
    <rsp:ReceiveResponse>
      <rsp:Stream Name='stdout' CommandId='BD6AA971-D33B-48A8-A1BC-E2B515770A89'>aGVsbG8gDQo=</rsp:Stream>
      <rsp:Stream Name='stdout' CommandId='BD6AA971-D33B-48A8-A1BC-E2B515770A89' End='true'/>
      <rsp:Stream Name='stderr' CommandId='BD6AA971-D33B-48A8-A1BC-E2B515770A89' End='true'/>
      <rsp:CommandState CommandId='BD6AA971-D33B-48A8-A1BC-E2B515770A89' State='http://schemas.microsoft.com/wbem/wsman/1/windows/shell/CommandState/Done'>
        <rsp:ExitCode>100</rsp:ExitCode>
      </rsp:CommandState>
    </rsp:ReceiveResponse>
  </s:Body>
```

**Comment by sneal** [comment] 2015-10-27 19:33
Well that's odd, I certainly wouldn't expect that.

**Comment by mwrock** [comment] 2015-10-28 22:06
started PR to fix this. It just has an integration test right now with a repro.

**Comment by mwrock** [comment] 2015-10-28 23:55
So I did some investigation here using the test referenced above. The WinRM response explicitly includes a `0` exit code so this gem is not parsing the response incorrectly. Researching the protocol, there appears to be no special message type indicating that you want just an exit code with no output and I also experimented with removing the `DesiredStream` element and also sending that element with empty content. Both of those attempts failed. Looks like they violate the wsdl.

Finally I used `winrs` to see what its behavior would be.

```
C:\> winrs -r:http://192.168.137.126:5985/wsman -u:vagrant -p:vagrant "echo hi `&& exit 100"
hi

C:\> $LASTEXITCODE
100
C:\> winrs -r:http://192.168.137.126:5985/wsman -u:vagrant -p:vagrant "echo hi"
hi

C:\> $LASTEXITCODE
0
```
So it appears that even the native windows winrm client has this same bug.

**Comment by carpnick** [comment] 2015-10-29 00:16
I am guessing this is not a client issue, but instead of service issue.  Because of how the response still looked correct I cannot say I am surprised that winrs also fails.  Thanks for looking into that.

I think this might be worth documenting as its a known edge condition.  Thoughts?  Kind of surprised me and I could imagine this could surprise others.

**Comment by carpnick** [comment] 2015-10-29 00:18
Thanks @mwrock for looking into it.

**Comment by carpnick** [comment] 2015-10-29 00:35
Reading this a bit closer your latest test case I think was incorrect.  You echoed instead of exited:

`
PS C:\Users\ncarpenter> $LASTEXITCODE
0
PS C:\Users\ncarpenter> winrs -r:localhost -u:Administrator -p:password "exit 100"

PS C:\Users\ncarpenter> $LASTEXITCODE
100
`

**Comment by mwrock** [comment] 2015-10-29 00:38
New info. This only reproduces for me on a windows 10 client. Windows 2012R2 exhibits the desired result. I have filed this bug: https://connect.microsoft.com/PowerShell/feedbackdetail/view/1956153/winrm-on-wmf-5-exits-0-always-if-a-command-has-no-standard-output on the Microsoft connect site.

**Comment by mwrock** [comment] 2015-10-29 00:39
@carpnick can you confirm the windows OS version from which you are issuing the request?

**Comment by carpnick** [comment] 2015-10-29 00:42
Windows 7(SP1) professional:
![image](https://cloud.githubusercontent.com/assets/6966179/10807285/5d5ea224-7db4-11e5-95a2-deabe93c1f46.png)

**Comment by mwrock** [comment] 2015-10-29 00:44
oh interesting. I wonder if it is related to client SKUs. I'll test different combos but win2012R2 <-> win2012R2 is definitely responding correctly for me.

**Comment by carpnick** [comment] 2015-10-29 00:52
Notice I was able to get it to do what was desired with winrs though.  I was able to get an exit of 100.  When I did a localhost winrs call on windows 7

**Comment by mwrock** [comment] 2015-10-29 00:55
Ok. yes I'm not having with `winrs` on win7 either. Will need to get a ruby environment going to find out more.

**Comment by mwrock** [comment] 2015-10-29 01:12
Cofirmed that windows 2012R2 via this gem does reproduce the exit code. Pulling down wireshark...

**Comment by mwrock** [comment] 2015-10-29 01:39
ok I have a saved unencrypted 5985 capture from both a winrs exit 100 result and a ruby exit 0 result. I have skimmed the captures to confirm the exit codes are in the dump. I'll analyze these more closely later on.

**Comment by sneal** [comment] 2015-10-29 15:05
@carpnick I think you need to pull in the latest WinRM gem. I can reproduce this issue on the 1.2 tag but not in master. I'm going to close this.

@mwrock Thanks for your help in trying to track down the issue.

**Comment by carpnick** [comment] 2015-10-29 15:56
Cloned this out at latest commit and still can reproduce:https://github.com/WinRb/WinRM/commit/6059c364f4a5c4c3d82616b7b2c9dcad178d862f ?

**Comment by mwrock** [comment] 2015-10-29 15:58
@sneal Odd. I reproduced from master last night on win2012R2. I took wireshark snapshots of it working via winrs and breaking in the gem and am gonna analyze them today.

**Comment by sneal** [comment] 2015-10-29 16:05
Perhaps I closed too soon then. I tried 3 OSs (Win2008R2, Win2008R2 SP1 patched, Win2012R2 patched) and was only able to repro this on an old WinRM gem version where the result handling was a little iffy.

**Comment by mwrock** [comment] 2015-10-29 21:15
I've been coming over the wireshark output [here](https://gist.github.com/mwrock/e55a9a6522d4ba9ade0f) and nothing obvious stands out. Both transcripts are from the same win2012R2 machine and addressed to the same windows 2012R2 endpoint. They both execute the same command. The winrs command exits 100 but the ruby script exits 0.

Both transcripts are strikingly similar. The key difference that stands out to me is that the winrs uses a sessionId, operationId and sequence while ruby does not. I have no idea if that is significant or not at this point - just an observation of something different.

I'm stepping away from this investigation for a bit.

**Comment by mwrock** [comment] 2015-10-31 18:39
I did some more investigation into this because I was super curious why this was happening. I hav to say these findings are not very satisfying.

I hacked WinRM to produce the exaxt same request format as winrs: adding sessionId, OperationID and SequenceId, using codepage 437 and a couple other option tweaks. This did not have any impact. At this point the only difference was basic auth vs. Negotiate.

Other observations:
- winrs occasionally returns a 0 exit code but mostly 100
- I did see one ruby call produce a 100 exit code but only one
- If I under provision the remote WinRM server (512MB Ram), then winrs consistently returns a 0 exit code

My hypothesis:
At this point I believe this is related to timing. There is no reason why the OS version of the client should have any impact on the ruby implementation since all the code is is a SOAP client. There is really nothing else at play outside the simple wire protocol exchange.

winrs is a C/C++ implementation and looking at the wireshark transcript, it sends the request for output consistently much faster than the ruby client. So possibly the exit code is swallowed if it is not requested quickly enough. I wish I had better data to back that up.

I'm leaning toward closing this since I don't think there is much that can be done in this gem to aleviate this. One possible approach would be to force something to standard out but that is certainly a hack that is probably best implemented on the consumer side of this gem.

**Closed by mwrock** 2015-10-31 18:39 UTC

**Comment by carpnick** [comment] 2015-11-01 00:03
Agreed @mwrock.  At least we know about this now, and it is documented with an issue.  I always thought this was mostly an edge condition anyways, but still could trip some people up.

Thanks for the investigation @mwrock and @sneal .

**Comment by jfhutchi-ibm** [comment] 2016-02-03 01:53
I've seen this issue on version 1.6.0 (endpoint is Win2008 SP2) but only when attempting to execute bat files on command line.

**Comment by kokovoj** [comment] 2016-07-29 21:53
>>If no output is returned in the winrm command, it always succeeds.

@carpnick - I completely agree with you that this is a wrong behavior. I am hitting this as well and for my use-case this is a completely wrong behavior. 

Specifically, I often pipe cmd output to findstr to parse it for idempotency conditions (with chef) and I rely on the OS for parsing (`!=0` exit code if no match). I am on Windows 2008 R2 and using winrm 1.5.0 gem. Simplest examples when run locally:

`C:\Users\Administrator>echo "foo" | findstr /C:"foo"`
`foo`

`C:\Users\Administrator>echo %errorlevel%`
`0`

`C:\Users\Administrator>echo "foo" | findstr /C:"bar"`

`C:\Users\Administrator>echo %errorlevel%`
`1`
and I was hoping for the same behavior remotely via winrm as well.

However, when I attempt same behavior via winrm gem I am getting 0 exit code in both cases :

`winrm.create_executor do |executor|`
`  output = executor.run_cmd( cmd ) do |stdout, stderr|`
`  end`
`end`

Case 1 (`cmd="echo foo | findstr /C:\"foo\""`)
`output={:data=>[{:stdout=>"foo \r\n"}], :exitcode=>0}`

Case 2 (`cmd="echo foo | findstr /C:\"bar\""`)
`output={:data=>[], :exitcode=>0}` (note :data array is empty)

So looks like I'll have to handle this case on my own in the WinRM client code above, by returning `!=0` exit code :
`if ((cmd contained findstr) and (there was no output - either data array is empty (output[:data].empty?) or stdout nil (output[:data][0][:stdout].nil?))`

Are there any alternatives ?

**Comment by mwrock** [comment] 2016-07-29 23:50
FWIW: I have tested this same scenario on the winrm-v2 branch and it still fails under the cmd shell but succeeds in powershell. Exit codes extraction is fundamentally different in the PSRP protocol implemented in the winrm-v2 branch and appear to be much more reliable. While @kokovoj is using a cmd based script, it could easily be converted to powershell.
