### ISSUE TITLE
Long running jobs fail due to recursion

### ISSUE THREAD

**Issue by skazzyy** [WinRb/WinRM#129] opened 2015-02-11 16:33 UTC
When running very long tasks (hours) that produce a lot of output through winrm, the job will eventually fail.  In previous versions of WinRM it threw an error stating
* stack level too deep (SystemStackError)
After upgrading to the latest gems, the error is now:
* ERROR: ThreadError: can't create Thread (12)

Running with debug leads to this [stack trace](https://gist.github.com/skazzyy/0ae01a20b3a038f25469)  The following line is in there about 1500 times.
* from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/winrm-1.2.0/lib/winrm/winrm_service.rb:179:in `get_command_output'

Easily (though takes time) reproduce with this line:
*  knife winrm %HOSTNAME% -x %USER_NAME% -P %PASSWORD% -m "ping /t localhost"

Right now I think the only workaround is to use winrs which means only running from a Windows machine which is not ideal.

**Comment by sneal** [comment] 2015-02-12 19:53
Thanks for reporting this. That does seem possible given the implementation.

**Comment by sneal** [comment] 2015-04-01 01:25
@skazzyy How long did you have to wait before it crashed?

**Comment by sneal** [comment] 2015-04-01 15:13
I couldn't reproduce this (probably wasn't patient enough), but it should be fixed. I replaced the recursive call with an iterative solution.

**Closed by sneal** 2015-04-01 15:13 UTC
Labels: bug

**Comment by skazzyy** [comment] 2015-04-01 15:28
When the new version is released I'll give it a try.  I'm sure if the recursion is gone the issue is gone.

Thanks!

**Comment by sneal** [comment] 2015-04-01 16:05
1.3.1 released
