### ISSUE TITLE
Unable to run sample script using Kerberos transport with winrm-2.1.0

### ISSUE THREAD

**Issue by aalblas** [WinRb/WinRM#236] opened 2016-10-13 19:33 UTC
I'm upgrading from 1.7.3, I see that the connection setup is a  little different.

I can get the sample to run 

require 'winrm'
opts = { 
  endpoint: 'http://myhost:5985/wsman',
  user: 'administrator',
  password: 'Pass@word1'
}
conn = WinRM::Connection.new(opts)
conn.shell(:powershell) do |shell|
  output = shell.run('$PSVersionTable') do |stdout, stderr|
    STDOUT.print stdout
    STDERR.print stderr
  end
  puts "The script exited with exit code #{output.exitcode}"
end

However if I change this to use kerberos:
opts = { 
  endpoint: 'http://myhost:5985/wsman',
  user: 'administrator',
  password: 'Pass@word1'
  realm: 'SOMEREALM.COM'
  transport: :kerberos
}

Then this fails with a decrypt error like below. Am I missing a parameter?

I tried adding :basic_auth_only and :disable_sspi however that made no difference.

stack trace below:

/usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/http/transport.rb:375:in `winrm_decrypt': 
undefined local variable or method`min_stat' for #WinRM::HTTP::HttpGSSAPI:0x007f462dd8cd48 (NameError)
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/http/transport.rb:289:in `send_request'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/power_shell.rb:152:in`max_envelope_size_kb'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/power_shell.rb:80:in `max_fragment_blob_size'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/power_shell.rb:198:in`fragmenter'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/power_shell.rb:162:in `block in open_shell_payload'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/power_shell.rb:161:in`map'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/power_shell.rb:161:in `open_shell_payload'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/power_shell.rb:122:in`open_shell'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/base.rb:163:in `block in open'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/retryable.rb:37:in`retryable'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/base.rb:161:in `open'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/base.rb:124:in`with_command_shell'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/shells/base.rb:80:in `run'
        from ./test.rb:12:in`block in <main>'
        from /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/connection.rb:43:in `shell'
        from ./test.rb:11:in`<main>'

**Comment by sneal** [comment] 2016-10-13 21:15
Unfortunately Kerberos doesn't have very good test coverage. It looks like an extract method refactoring in [this commit](https://github.com/WinRb/WinRM/commit/4aa0c739c2cc28d21e08ef35c63f556f9a4ceecd#diff-dc09b41ae42a97b2acbfa31d5f918d71) broke the logging statement.

**Comment by makushimu** [comment] 2016-11-23 00:36
I hit this same bug after upgrading to the latest chef-dk.
Sadly, the problem is a bit deeper than just commenting the logging statement. I tested by just commenting out the broken logging statement, and the command still failed. From what I tested, the output of the `winrm_decrypt` function isn't decrypted.

It seems to be limited to `winrm_decrypt`, since if I monkeypatch to put the "old" version in, it works.

**Comment by alv000h** [comment] 2017-01-10 17:14
+1

**Comment by juanjomm** [comment] 2017-01-11 09:46
+1

**Comment by mwrock** [comment] 2017-01-12 08:13
I'll admit that I have never used kerberos. I have restored the kerberos encryption/decryption to its state in v1.8.1. Can someone test against PR #245 and report if that fixes kerberos connections? If you are unsure how to do that, I can provide instructions. Thanks!

**Comment by aalblas** [comment] 2017-01-12 14:50
If you can provide some instructions on how to test against PR #245 then I can help.

**Comment by mwrock** [comment] 2017-01-12 17:28
Sure thing @aalblas so here are a couple methods and you can choose the one you feel most comfortable with:

## Method 1 (bundler)
Add this to a Gemfile:
```
gem 'winrm-', github: 'winrb/winrm', branch: 'kerberos'
```

Then run `bundle install followed by `bundle exec irb` and try the sample code from the readme.

## Method 2 (brute copy):
Simply copy all content from https://raw.githubusercontent.com/WinRb/WinRM/4c91e208f3f2f89a21edcf6840fdc628bca3e0a7/lib/winrm/http/transport.rb to /usr/local/lib/ruby/gems/2.1.0/gems/winrm-2.1.0/lib/winrm/http/transport.rb and then run the sample script.

If you use method 2, make sure to uninstall and reinstall the gem if it still fails.

**Comment by aalblas** [comment] 2017-01-12 18:37
This worked correctly, I tested this against winrm-2.1.1 

The sample script worked successfully against kerberos, I also validated winrm-fs, this also transferred the files using kerberos authetnication.

Thank you!

**Comment by mwrock** [comment] 2017-01-12 19:12
Thanks so much for reporting! I'll get a release out later today with the fix.

**Comment by mwrock** [comment] 2017-01-13 05:11
fixed via #245

**Closed by mwrock** 2017-01-13 05:11 UTC
Labels: bug
